'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
            If My.Application.SaveMySettingsOnExit Then
                My.Settings.Save()
            End If
        End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save1Player1() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save1Player1"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save1Player1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save1Player2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save1Player2"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save1Player2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save1Player3() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save1Player3"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save1Player3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save1Player4() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save1Player4"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save1Player4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save1Player5() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save1Player5"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save1Player5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save1Player6() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save1Player6"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save1Player6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save1Index1() As Integer
            Get
                Return CType(Me("Save1Index1"), Integer)
            End Get
            Set(value As Integer)
                Me("Save1Index1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save1Index2() As Integer
            Get
                Return CType(Me("Save1Index2"), Integer)
            End Get
            Set(value As Integer)
                Me("Save1Index2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save1Index3() As Integer
            Get
                Return CType(Me("Save1Index3"), Integer)
            End Get
            Set(value As Integer)
                Me("Save1Index3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save1Index4() As Integer
            Get
                Return CType(Me("Save1Index4"), Integer)
            End Get
            Set(value As Integer)
                Me("Save1Index4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save1Index5() As Integer
            Get
                Return CType(Me("Save1Index5"), Integer)
            End Get
            Set(value As Integer)
                Me("Save1Index5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save1Index6() As Integer
            Get
                Return CType(Me("Save1Index6"), Integer)
            End Get
            Set(value As Integer)
                Me("Save1Index6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save2Player1() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save2Player1"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save2Player1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save2Player2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save2Player2"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save2Player2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save2Player3() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save2Player3"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save2Player3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save2Player4() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save2Player4"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save2Player4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save2Player5() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save2Player5"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save2Player5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save2Player6() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save2Player6"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save2Player6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save2Index1() As Integer
            Get
                Return CType(Me("Save2Index1"), Integer)
            End Get
            Set(value As Integer)
                Me("Save2Index1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save2Index2() As Integer
            Get
                Return CType(Me("Save2Index2"), Integer)
            End Get
            Set(value As Integer)
                Me("Save2Index2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save2Index3() As Integer
            Get
                Return CType(Me("Save2Index3"), Integer)
            End Get
            Set(value As Integer)
                Me("Save2Index3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save2Index4() As Integer
            Get
                Return CType(Me("Save2Index4"), Integer)
            End Get
            Set(value As Integer)
                Me("Save2Index4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save2Index5() As Integer
            Get
                Return CType(Me("Save2Index5"), Integer)
            End Get
            Set(value As Integer)
                Me("Save2Index5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save2Index6() As Integer
            Get
                Return CType(Me("Save2Index6"), Integer)
            End Get
            Set(value As Integer)
                Me("Save2Index6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save3Player1() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save3Player1"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save3Player1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save3Player2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save3Player2"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save3Player2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save3Player3() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save3Player3"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save3Player3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save3Player4() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save3Player4"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save3Player4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save3Player5() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save3Player5"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save3Player5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save3Player6() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save3Player6"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save3Player6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save3Index1() As Integer
            Get
                Return CType(Me("Save3Index1"), Integer)
            End Get
            Set(value As Integer)
                Me("Save3Index1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save3Index2() As Integer
            Get
                Return CType(Me("Save3Index2"), Integer)
            End Get
            Set(value As Integer)
                Me("Save3Index2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save3Index3() As Integer
            Get
                Return CType(Me("Save3Index3"), Integer)
            End Get
            Set(value As Integer)
                Me("Save3Index3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save3Index4() As Integer
            Get
                Return CType(Me("Save3Index4"), Integer)
            End Get
            Set(value As Integer)
                Me("Save3Index4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save3Index5() As Integer
            Get
                Return CType(Me("Save3Index5"), Integer)
            End Get
            Set(value As Integer)
                Me("Save3Index5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save3Index6() As Integer
            Get
                Return CType(Me("Save3Index6"), Integer)
            End Get
            Set(value As Integer)
                Me("Save3Index6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save4Player1() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save4Player1"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save4Player1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save4Player2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save4Player2"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save4Player2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save4Player3() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save4Player3"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save4Player3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save4Player4() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save4Player4"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save4Player4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save4Player5() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save4Player5"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save4Player5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save4Player6() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save4Player6"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save4Player6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save4Index1() As Integer
            Get
                Return CType(Me("Save4Index1"), Integer)
            End Get
            Set(value As Integer)
                Me("Save4Index1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save4Index2() As Integer
            Get
                Return CType(Me("Save4Index2"), Integer)
            End Get
            Set(value As Integer)
                Me("Save4Index2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save4Index3() As Integer
            Get
                Return CType(Me("Save4Index3"), Integer)
            End Get
            Set(value As Integer)
                Me("Save4Index3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save4Index4() As Integer
            Get
                Return CType(Me("Save4Index4"), Integer)
            End Get
            Set(value As Integer)
                Me("Save4Index4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save4Index5() As Integer
            Get
                Return CType(Me("Save4Index5"), Integer)
            End Get
            Set(value As Integer)
                Me("Save4Index5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save4Index6() As Integer
            Get
                Return CType(Me("Save4Index6"), Integer)
            End Get
            Set(value As Integer)
                Me("Save4Index6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save5Player1() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save5Player1"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save5Player1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save5Player2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save5Player2"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save5Player2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save5Player3() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save5Player3"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save5Player3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save5Player4() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save5Player4"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save5Player4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save5Player5() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save5Player5"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save5Player5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Save5Player6() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Save5Player6"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set(value As Global.System.Collections.Specialized.StringCollection)
                Me("Save5Player6") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save5Index1() As Integer
            Get
                Return CType(Me("Save5Index1"), Integer)
            End Get
            Set(value As Integer)
                Me("Save5Index1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save5Index2() As Integer
            Get
                Return CType(Me("Save5Index2"), Integer)
            End Get
            Set(value As Integer)
                Me("Save5Index2") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save5Index3() As Integer
            Get
                Return CType(Me("Save5Index3"), Integer)
            End Get
            Set(value As Integer)
                Me("Save5Index3") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save5Index4() As Integer
            Get
                Return CType(Me("Save5Index4"), Integer)
            End Get
            Set(value As Integer)
                Me("Save5Index4") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save5Index5() As Integer
            Get
                Return CType(Me("Save5Index5"), Integer)
            End Get
            Set(value As Integer)
                Me("Save5Index5") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property Save5Index6() As Integer
            Get
                Return CType(Me("Save5Index6"), Integer)
            End Get
            Set(value As Integer)
                Me("Save5Index6") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")> _
        Friend ReadOnly Property Settings() As Global.Video_Wall.My.MySettings
            Get
                Return Global.Video_Wall.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
